# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

cppbackward <- function(k, NUMA, maxdonors, THIN, NUMP, L, gl, gu, G, transitions, UMATCH, max_umatch_size, dw, tw, gobs, mutmat, maxmiss, label, kndonors, donates, donatesr, flips, backs, scalefactor) {
    invisible(.Call(`_MOSAIC_cppbackward`, k, NUMA, maxdonors, THIN, NUMP, L, gl, gu, G, transitions, UMATCH, max_umatch_size, dw, tw, gobs, mutmat, maxmiss, label, kndonors, donates, donatesr, flips, backs, scalefactor))
}

cpp_unique_haps <- function(Y, k, S, G, gmap, maxgmap, uhaps) {
    .Call(`_MOSAIC_cpp_unique_haps`, Y, k, S, G, gmap, maxgmap, uhaps)
}

cppforback <- function(maxdonors, THIN, NUMP, L, G, ndonors, donates, fors, backs) {
    .Call(`_MOSAIC_cppforback`, maxdonors, THIN, NUMP, L, G, ndonors, donates, fors, backs)
}

cppgforback <- function(maxdonors, THIN, kLL, NUMP, label, L, G, ndonors, donates, fors, backs) {
    .Call(`_MOSAIC_cppgforback`, maxdonors, THIN, kLL, NUMP, label, L, G, ndonors, donates, fors, backs)
}

cppforward <- function(k, NUMA, maxdonors, THIN, NUMP, kLL, L, gl, gu, G, transitions, UMATCH, max_umatch_size, dw, tw, gobs, mutmat, maxmiss, initProb, label, kndonors, donates, donatesl, flips, fors, sumfors, scalefactor) {
    invisible(.Call(`_MOSAIC_cppforward`, k, NUMA, maxdonors, THIN, NUMP, kLL, L, gl, gu, G, transitions, UMATCH, max_umatch_size, dw, tw, gobs, mutmat, maxmiss, initProb, label, kndonors, donates, donatesl, flips, fors, sumfors, scalefactor))
}

cppprobs <- function(k, NUMA, maxdonors, THIN, L, kLL, NN, NUMP, G, label, fors, sumfors, backs, transitions, flips, mutmat, maxmiss, UMATCH, max_umatch_size, dw, tw, gobs, kndonors, donates, donatesl) {
    .Call(`_MOSAIC_cppprobs`, k, NUMA, maxdonors, THIN, L, kLL, NN, NUMP, G, label, fors, sumfors, backs, transitions, flips, mutmat, maxmiss, UMATCH, max_umatch_size, dw, tw, gobs, kndonors, donates, donatesl)
}

cppswitches <- function(k, NUMA, maxdonors, THIN, NUMP, G, NL, label, sumfors, backs, transitions, flips, mutmat, maxmiss, UMATCH, max_umatch_size, dw, tw, gobs, kndonors, donates) {
    .Call(`_MOSAIC_cppswitches`, k, NUMA, maxdonors, THIN, NUMP, G, NL, label, sumfors, backs, transitions, flips, mutmat, maxmiss, UMATCH, max_umatch_size, dw, tw, gobs, kndonors, donates)
}

